### ISSUE TITLE
Mobile layout: dialog issues

### ISSUE THREAD

**Issue by BedWords** [le-doux/bitsy#146]
![Screenshot_20220325-212826_Opera](https://user-images.githubusercontent.com/44188707/160219486-31914bee-d2a7-4c08-9937-968406afee37.jpg)
![Screenshot_20220325-212857_Opera](https://user-images.githubusercontent.com/44188707/160219642-dd500de3-7c53-411b-800e-9a042ff2c913.jpg)

A few issues in one here. The first two are just a bit annoying, but the third makes it unusable on mobile if you're scripting.
If I am viewing a dialog script on mobile, the text box goes beyond the panel, hiding some text (pic 1). When I bring focus to the textbox, the panel stretches beyond the screen (pic 2).

If I navigate away from that dialog to another, or hide code and then view code, some of the variables get removed. (script was originally just checking the item count for the key item). Also seems to remove code blocks put within if/else statements, though they work if you test them before switching dialogs.

**Comment by iandoesallthethings** [comment]
Found the reason for the first problem! It looks like the mobile/desktop css rules switch on max-aspect-ratio. On android, the viewport changes when the keyboard opens, so it jumps back to desktop mode when you start typing!

```css
.bitsy-card-m .bitsy-card-main {
    width: var(--bitsy-size-m); 
}

@media (max-aspect-ratio: 3 / 4) 
.bitsy-card .bitsy-card-main {
    width: calc(100% - (2 * var(--bitsy-space-m)));
}
```
